import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  site: 'https://amalficoast-travel.com',
  integrations: [
    tailwind(),
  ],
  i18n: {
    defaultLocale: 'en-us',
    locales: ['en-us', 'de-de', 'fr-fr', 'es-es', 'it-it'],
    routing: {
      prefixDefaultLocale: true,
    },
  },
  redirects: {
    // --- SEZIONE PLANNING (Mappatura precisa per lingua) ---
    '/en-us/planification/': '/en-us/planning/',
    '/en-us/pianificazione/': '/en-us/planning/',
    '/it-it/planning/': '/it-it/pianificazione/',
    '/it-it/planification/': '/it-it/pianificazione/',
    '/de-de/planning/': '/de-de/planung/',
    '/de-de/planification/': '/de-de/planung/',
    '/de-de/pianificazione/': '/de-de/planung/',
    '/es-es/planning/': '/es-es/planificacion/',
    '/es-es/pianificazione/': '/es-es/planificacion/',
    '/fr-fr/planning/': '/fr-fr/planification/',
    '/fr-fr/pianificazione/': '/fr-fr/planification/',

    // --- SEZIONE ISOLE & DESTINAZIONI ---
    '/en-us/isole/': '/en-us/islands/',
    '/en-us/isole/procida/': '/en-us/islands/procida/',
    '/en-us/isole/capri/': '/en-us/islands/capri/',
    '/en-us/procida/': '/en-us/islands/procida/',
    '/en-us/capri/': '/en-us/islands/capri/',
    '/en-us/ischia/': '/en-us/islands/ischia/',
    '/de-de/isole/capri/': '/de-de/islands/capri/',
    '/de-de/ischia/': '/de-de/islands/ischia/',
    '/de-de/procida/': '/de-de/islands/procida/',
    '/de-de/anacapri/': '/de-de/islands/anacapri/',
    '/es-es/isole/': '/es-es/islas/',
    '/es-es/isole/capri/': '/es-es/islas/capri/',
    '/es-es/ischia/': '/es-es/islas/ischia/',
    '/es-es/procida/': '/es-es/islas/procida/',
    '/fr-fr/isole/capri/': '/fr-fr/isles/capri/',
    '/fr-fr/ischia/': '/fr-fr/isles/ischia/',
    '/fr-fr/capri/': '/fr-fr/isles/capri/',
    '/fr-fr/anacapri/': '/fr-fr/isles/anacapri/',
    '/it-it/ischia/': '/it-it/isole/ischia/',
    '/it-it/capri/': '/it-it/isole/capri/',

    // --- AMALFI COAST & BEACHES (Fix slug e caratteri speciali) ---
    '/de-de/amalfiküste/': '/de-de/amalfikueste/',
    '/de-de/amalfiküste/amalfi/': '/de-de/amalfikueste/amalfi/',
    '/de-de/amalfiküste/positano/': '/de-de/amalfikueste/positano/',
    '/de-de/amalfiküste/maiori/': '/de-de/amalfikueste/maiori/',
    '/de-de/amalfiküste/ravello/': '/de-de/amalfikueste/ravello/',
    '/de-de/amalfiküste/vietri-sul-mare/': '/de-de/amalfikueste/vietri-sul-mare/',
    '/de-de/amalfiküste/minori/': '/de-de/amalfikueste/minori/',
    '/de-de/amalfi-coast/amalfi/': '/de-de/amalfikueste/amalfi/',
    '/de-de/amalfi-coast/positano/': '/de-de/amalfikueste/positano/',
    '/de-de/strände/amalfiküste/spiaggia-grande-positano/': '/de-de/straende/amalfikueste/spiaggia-grande-positano/',
    '/de-de/strände/amalfiküste/fiordo-di-furore/': '/de-de/straende/amalfikueste/fiordo-di-furore/',
    '/de-de/strände/inseln/marina-piccola-capri/': '/de-de/straende/islands/marina-piccola-capri/',
    '/de-de/spiagge/': '/de-de/straende/',
    '/es-es/costiera-amalfitana/': '/es-es/costa-amalfitana/',
    '/es-es/costiera-amalfitana/positano/': '/es-es/costa-amalfitana/positano/',
    '/es-es/costiera-amalfitana/amalfi/': '/es-es/costa-amalfitana/amalfi/',
    '/es-es/costiera-amalfitana/maiori/': '/es-es/costa-amalfitana/maiori/',
    '/es-es/costiera-amalfitana/ravello/': '/es-es/costa-amalfitana/ravello/',
    '/es-es/costiera-amalfitana/vietri-sul-mare/': '/es-es/costa-amalfitana/vietri-sul-mare/',
    '/es-es/costiera-amalfitana/minori/': '/es-es/costa-amalfitana/minori/',
    '/es-es/amalfi-coast/positano/': '/es-es/costa-amalfitana/positano/',
    '/es-es/amalfi-coast/amalfi/': '/es-es/costa-amalfitana/amalfi/',
    '/es-es/spiagge/': '/es-es/playas/',
    '/fr-fr/spiagge/': '/fr-fr/plages/',

    // --- PENISOLA SORRENTINA ---
    '/en-us/sorrentine-peninsula/sorrento/': '/en-us/sorrento-peninsula/sorrento/',
    '/en-us/sorrentine-peninsula/massa-lubrense/': '/en-us/sorrento-peninsula/massa-lubrense/',
    '/en-us/sorrentine-peninsula/sant-agnello/': '/en-us/sorrento-peninsula/sant-agnello/',
    '/en-us/sorrentine-peninsula/vico-equense/': '/en-us/sorrento-peninsula/vico-equense/',
    '/fr-fr/peninsule-sorrentine/sorrento/': '/fr-fr/peninsule-sorrentine/sorrente/',
    '/fr-fr/peninsule-sorrentine/sorrent/': '/fr-fr/peninsule-sorrentine/sorrente/',
    '/de-de/sorrentinische-halbinsel/sorrento/': '/de-de/sorrento-peninsula/sorrento/',
    '/de-de/sorrentinische-halbinsel/sorrente/': '/de-de/sorrento-peninsula/sorrento/',
    '/es-es/penisola-sorrentina/sorrente/': '/es-es/peninsula-sorrentina/sorrento/',
    '/es-es/peninsula-sorrentina/sorrent/': '/es-es/peninsula-sorrentina/sorrento/',

    // --- GUIDE & TRAGHETTI ---
    '/en-us/guide/how-to-get-there/': '/en-us/guide/how-to-get-here/',
    '/de-de/guida/anreise/': '/de-de/reisefuehrer/anreise/',
    '/de-de/guida/beste-reisezeit/': '/de-de/reisefuehrer/beste-reisezeit/',
    '/de-de/ratgeber/wie-man-anreist/': '/de-de/reisefuehrer/anreise/',
    '/de-de/reiseführer/faehren/': '/de-de/reisefuehrer/faehren/',
    '/de-de/quando-visitare/': '/de-de/reisefuehrer/beste-reisezeit/',
    '/fr-fr/guide/comment-arriver/': '/fr-fr/guide/comment-se-rendre/',
    '/fr-fr/guide/comment-sy-rendre/': '/fr-fr/guide/comment-se-rendre/',
    '/fr-fr/quando-visitare/': '/fr-fr/guide/quand-partir/',
    '/fr-fr/quand-visiter/': '/fr-fr/guide/quand-partir/',
    '/es-es/guia/ferrys/': '/es-es/guia/ferries/',
    '/es-es/guia/traghetti/': '/es-es/guia/ferries/',
    '/es-es/quando-visitare/': '/es-es/guia/mejor-epoca-para-viajar/',

    // --- BLOG & ESPERIENZE ---
    '/en-us/blog/ferriere-valley-trekking/': '/en-us/blog/valle-delle-ferriere-hiking/',
    '/it-it/blog/cetara-acciughe/': '/it-it/blog/colatura-alici-cetara/',
    '/fr-fr/blog/cetara-anchois/': '/fr-fr/blog/colatura-anchois-cetara/',
    '/es-es/blog/cetara-anchovetas/': '/es-es/blog/colatura-anchoas-cetara/',
    '/fr-fr/experiences/cours-cuisine/': '/fr-fr/experiences/cours-de-cuisine/',
    '/es-es/experiencias/clase-de-cocina/': '/es-es/experiencias/clases-de-cocina/',
    '/de-de/erlebnisse/mozzarella-experience/': '/de-de/erlebnisse/mozzarella-tour/',
    '/en-us/itineraries/1-day/path-of-the-gods/': '/en-us/itineraries/path-of-the-gods-hiking/',
  },
});
