/**
 * Remove escaped apostrophes from strings (e.g., "L\'italiano" -> "L'italiano")
 * Useful for cleaning up strings generated by Claude AI
 */
export function cleanEscapedApostrophes(text: string): string {
  return text.replace(/\\'/g, "'");
}

/**
 * Remove escaped quotes from strings
 */
export function cleanEscapedQuotes(text: string): string {
  return text.replace(/\\"/g, '"');
}

/**
 * Clean all escaped characters from a string
 */
export function cleanEscapedChars(text: string): string {
  return text
    .replace(/\\'/g, "'")
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, '\\');
}
